### ISSUE TITLE
Not working with new Logitech drivers

### ISSUE THREAD

**Issue by erkswede** [chrilith/Passerelle#3]
Hi

Logitech has issued "new" drivers, v 8.0.116.0, for the X52 Pro joystick: http://support.logitech.com/en_us/product/x52-space-flight-simulator-controller/downloads

I can't get passerelle to work with this driver. I have only tested 64-bit. 

Any chance  of an update?

I have made a "plugin" for X-Plane that is depending on passerelle and more and more users wants to update their drivers.

Here's my plugin: https://forums.x-plane.org/index.php?/files/file/35304-x52luaout-winmaclin/

Kind regards and a happy new year!
/Erik

PS Therese are new drivers for the instrument panels as well, but I don't use these so I don't know if there is an issue there as well.

**Comment by chrilith** [comment]
Hi @erkswede and happy new year!

Could you tell me if there is a SDK folder or something like that in you X52 installation folder? As stated in your previous issue #2, I don't own a X52 and it is difficult for me to test :)

Also, don't know it Logitech kept support for DirectOutput with latest drivers...

Thank you
Chris

**Comment by erkswede** [comment]
Hi

Indeed there is a SDK folder in C:\Program Files\Logitech\DirectOutput\SDK The content seems to be much the same as previous Saitek versions, but I haven't dug deeper in what changed. 

Shall I send it to you?
Kind Regards
/Erik

**Comment by chrilith** [comment]
Yes, please I'll try to check the changes.

**Comment by erkswede** [comment]
OK, here it comes. This is everything I found in "Program Files/Logitech" regarding the X52 Pro.
Let me know if I can help you in any way.
[X52 Professional.zip](https://github.com/chrilith/Passerelle/files/1601057/X52.Professional.zip)

**Comment by chrilith** [comment]
OK, thank you, will check it!

**Comment by erkswede** [comment]
Hi.
Have you been able to find a solution?
Cheers
/Erik

**Comment by chrilith** [comment]
Hi,

Well, I finally fixed this issue. There are 2 items here:
- Change in registry key
- Fact that the x86 version is not installed anymore with x64 drivers

This last point can be fixed using the workaround found in the documentation [here](https://github.com/chrilith/Passerelle/wiki/Drivers-Compatibility).

This fix will be part of the next release. Let me know if you wanna try right now.

Thanks

**Comment by erkswede** [comment]
Hi

Great that this is being fixed. 
However, I don't use Passerelle anymore as I needed a solution that is platform independent. So I don't need to try it at this point.

Kind regards
/Erik

**Comment by chrilith** [comment]
OK no problem ;)

Will close this issue. Thanks!
